### ISSUE TITLE
.

### ISSUE THREAD

**Issue by aid95** [zkzkzhzj/StandardJava#1]

**Comment by zkzkzhzj** [comment]
> 이 상태로는 보도방 SI도 취업 못할 것 같아서 공부하는 중
아 아놔 ㅋㅋㅋㅋ 말을하고 가라고 나 손절당한줄알고, 차단당했넹ㅎ.ㅋ 하고 있었는데

난 요새 자바를 깊게 파는게 맞는지 고민중이다..
나중에 안드로이드 말고 스프링도 해보고싶긴한데.. 당장에 안드로이드는 코틀린을 밀고있으니..
자바보는게 틀린선택인가.. 그냥 그런이야기나 할까했거든

암튼 그렇다니 열공해라

**Comment by aid95** [comment]
당빠 코틀린이지 요즘은 스프링도 코틀린으로 넘어가는 중인데

**Comment by zkzkzhzj** [comment]
> 당빠 코틀린이지 요즘은 스프링도 코틀린으로 넘어가는 중인데, 그런데 코틀린 공부하다 보면 결국은 자바도 공부하게 되더라

너 생각엔 이펙티브 자바, 자바 최적화 같은 책 보는건 어떻게 생각하냐.
순수히 자바 기초만 보고 넘기는게 지금 시대엔 맞나 싶다 ㅋㅋㅋㅋ

자바 공부한게 쓸모없어질까? 

아휴 지금알 수 있는건 없지 당장에 2년전만해도 코틀린이 이렇게 뜰줄 대부분 몰랐는데 ㅋㅋㅋㅋㅋ
저 책 본다고 손해보는건 없으니 봐도 괜찮겠지

**Comment by aid95** [comment]
내 생각보단 우형테크코스 강사님 말을 빌리면 모던 자바는 정독, 이펙티브 자바는 필요한 내용 찾아보는 용도로 보라고 하시던데, 자바 최적화는 너가 jvm을 엄청 최적화를 필요로 하는게 아니면 다른 부분에 더 집중하는게 좋지 않을까?

텔레그램 @bcake0 친추 줭
